/* Kindle notebook scraper — run via Control_Chrome.execute_javascript on the
 * read.amazon.com/notebook tab (with the target book loaded).
 *
 * Scrapes every highlight + book metadata and triggers a Blob download of
 * <asin>_highlights.json to ~/Downloads. Returns a small summary object.
 *
 * Why a download instead of returning the data: 466 highlights ~= 200-230 KB,
 * which exceeds tool-result limits and (if regenerated by the model) risks
 * corrupting verbatim text. The download keeps the bytes exact.
 *
 * If the file doesn't appear in ~/Downloads, the tab was a background tab —
 * Control_Chrome.switch_to_tab to make it active, then re-run.
 */
(() => {
  const norm = s => s ? s.replace(/ /g, ' ').replace(/\s+/g, ' ').trim() : s;

  const rows = [...document.querySelectorAll('#kp-notebook-annotations .kp-notebook-row-separator')];
  const highlights = rows.map(r => {
    const loc = r.querySelector('#kp-annotation-location')?.value || null;
    const header = norm(r.querySelector('#annotationHighlightHeader')?.textContent) || null; // "Yellow highlight | Location: 184"
    const color = header ? (header.split(' ')[0] || '').toLowerCase() : null;
    const hl = r.querySelector('span#highlight');
    const text = hl ? norm(hl.textContent) : null;
    const note = norm(r.querySelector('#note')?.textContent) || '';
    const truncated = r.textContent.includes('hidden or truncated due to export limits');
    return { loc: loc ? Number(loc) : null, color, text, note, truncated };
  }).filter(d => d.text !== null);

  // Best-effort book metadata (fill edition/publisher/year by hand in the build step).
  const titleEl = document.querySelector('h3.kp-notebook-metadata, #kp-notebook-annotations h3, h3.a-spacing-top-small');
  const authorEl = document.querySelector('#kp-notebook-annotations p.a-color-secondary, p.kp-notebook-metadata.a-color-secondary');
  const asin = new URLSearchParams(location.search).get('asin')
    || (document.querySelector('a[href*="/dp/"]')?.href.match(/\/dp\/([A-Z0-9]{10})/) || [])[1]
    || null;

  const payload = {
    book: { title: norm(titleEl?.textContent) || document.title, author: norm(authorEl?.textContent) || null, asin },
    count: highlights.length,
    truncated: highlights.filter(h => h.truncated).length,
    highlights,
  };

  const blob = new Blob([JSON.stringify(payload)], { type: 'application/json' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = (asin || 'kindle') + '_highlights.json';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 2000);

  return JSON.stringify({ downloaded: a.download, count: payload.count, truncated: payload.truncated, book: payload.book });
})()
